### ISSUE TITLE
Invalid registration attempt

### ISSUE THREAD

**Issue by LlubNek** [Darkhax-Minecraft/Bookshelf#113]
```
00:42:56 | FML | Client thread | warn | ****************************************
00:42:56 | FML | Client thread | warn | * Invalid registration attempt for an Ore Dictionary item with name hopper has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
00:42:56 | FML | Client thread | warn | *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:660)
00:42:56 | FML | Client thread | warn | *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:646)
00:42:56 | FML | Client thread | warn | *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:645)
00:42:56 | FML | Client thread | warn | *  at net.darkhax.bookshelf.util.OreDictUtils.initAdditionalVanillaEntries(OreDictUtils.java:366)
00:42:56 | FML | Client thread | warn | *  at net.darkhax.bookshelf.Bookshelf.init(Bookshelf.java:59)
00:42:56 | FML | Client thread | warn | *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
00:42:56 | FML | Client thread | warn | ****************************************
```

I found this while trying to pin down an error with EnderIO recipe files, but it seems to be unrelated.

[latest.log](https://github.com/Darkhax-Minecraft/Bookshelf/files/2674682/latest.log)

**Comment by darkhax** [comment]
Thanks for the issue report. It looks like another mod is removing the vanilla hopper in an unsafe way.
