### ISSUE TITLE
I'm not really sure whats happening

### ISSUE THREAD

**Issue by 8Neptune8** [Darkhax-Minecraft/Bookshelf#151]
I need the bookshelf mod for the EnchantingPlus mod but it keeps crashing for me. But if it's not there then it tells me i need to. PS: this is for mc 1.12.2

I do have the log if anyone that is helping wants it

**Comment by 8Neptune8** [comment]
[22:16:51] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[22:16:51] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[22:16:51] [main/DEBUG]: Coremod plugin class FMLCorePlugin run successfully
[22:16:51] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:16:51] [main/DEBUG]: Injecting coremod FMLForgePlugin \{net.minecraftforge.classloading.FMLForgePlugin\} class transformers
[22:16:51] [main/DEBUG]: Injection complete
[22:16:51] [main/DEBUG]: Running coremod plugin for FMLForgePlugin \{net.minecraftforge.classloading.FMLForgePlugin\}
[22:16:51] [main/DEBUG]: Running coremod plugin FMLForgePlugin
[22:16:51] [main/DEBUG]: Coremod plugin class FMLForgePlugin run successfully
[22:16:51] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:16:51] [main/DEBUG]: Injecting coremod ForgelinPlugin \{net.shadowfacts.forgelin.preloader.ForgelinPlugin\} class transformers
[22:16:51] [main/DEBUG]: Injection complete
[22:16:51] [main/DEBUG]: Running coremod plugin for ForgelinPlugin \{net.shadowfacts.forgelin.preloader.ForgelinPlugin\}
[22:16:51] [main/DEBUG]: Running coremod plugin ForgelinPlugin
[22:16:51] [main/DEBUG]: Coremod plugin class ForgelinPlugin run successfully
[22:16:51] [main/INFO]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[22:16:51] [main/INFO]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@681adc8f
[22:16:51] [main/DEBUG]: Injecting coremod MalisisCorePlugin \{net.malisis.core.asm.MalisisCorePlugin\} class transformers
[22:16:51] [main/DEBUG]: Injection complete
[22:16:51] [main/DEBUG]: Running coremod plugin for MalisisCorePlugin \{net.malisis.core.asm.MalisisCorePlugin\}
[22:16:51] [main/DEBUG]: Running coremod plugin MalisisCorePlugin
[22:16:51] [main/DEBUG]: Coremod plugin class MalisisCorePlugin run successfully
[22:16:51] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:16:51] [main/DEBUG]: Injecting coremod CXLibraryCore \{cubex2.cxlibrary.CoreModLoader\} class transformers
[22:16:51] [main/TRACE]: Registering transformer cubex2.cxlibrary.CoreModTransformer
[22:16:51] [main/DEBUG]: Injection complete
[22:16:51] [main/DEBUG]: Running coremod plugin for CXLibraryCore \{cubex2.cxlibrary.CoreModLoader\}
[22:16:51] [main/DEBUG]: Running coremod plugin CXLibraryCore
[22:16:51] [main/DEBUG]: Coremod plugin class CoreModLoader run successfully
[22:16:51] [main/INFO]: Calling tweak class guichaguri.betterfps.tweaker.BetterFpsTweaker
[22:16:51] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[22:16:51] [main/DEBUG]: Validating minecraft
[22:16:51] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:16:51] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:16:51] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:16:51] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:16:51] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:16:51] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[22:16:51] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[22:16:51] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[22:16:51] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[22:16:52] [main/INFO]: [team.chisel.ctm.client.asm.CTMTransformer:preTransform:230]: Transforming Class [net.minecraft.client.renderer.texture.TextureMap], Method [registerSprite]
[22:16:52] [main/INFO]: [team.chisel.ctm.client.asm.CTMTransformer:finishTransform:242]: Transforming net.minecraft.client.renderer.texture.TextureMap Finished.
[22:16:52] [main/INFO]: [techguns.core.TechgunsASMTransformer:patchRenderItem_patchMethodRenderModel:480]: Successfully patched 2 arg RenderItem.RenderModel with ASM
[22:16:52] [main/INFO]: [techguns.core.TechgunsASMTransformer:patchRenderItem_patchMethodRenderItem:299]: Successfully patched 4 arg RenderItem.RenderItem with ASM
[22:16:52] [main/INFO]: [techguns.core.TechgunsASMTransformer:patchRenderItem_patchMethodRenderItemGUI:423]: Successfully patched RenderItem.renderItemModelIntoGUI with ASM
[22:16:52] [main/INFO]: A re-entrant transformer '$wrapper.techguns.core.TechgunsASMTransformer' was detected and will no longer process meta class data
[22:16:52] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[22:16:52] [main/INFO]: Patching net.minecraft.client.Minecraft... (bib)
[22:16:52] [main/INFO]: Patching net.minecraft.block.Block... (aow)
[22:16:52] [main/INFO]: [team.chisel.ctm.client.asm.CTMTransformer:preTransform:230]: Transforming Class [net.minecraft.block.Block], Method [getExtendedState]
[22:16:52] [main/INFO]: [team.chisel.ctm.client.asm.CTMTransformer:finishTransform:242]: Transforming net.minecraft.block.Block Finished.
[22:16:52] [main/INFO]: Patching net.minecraft.client.entity.EntityPlayerSP... (bud)
[22:16:53] [main/INFO]: [net.minecraft.client.main.Main:main:55]: Completely ignored arguments: [1.8, ]
[22:16:53] [main/INFO]: [team.chisel.ctm.client.asm.CTMTransformer:preTransform:230]: Transforming Class [net.minecraftforge.client.ForgeHooksClient], Method [getDamageModel]
[22:16:53] [main/INFO]: [team.chisel.ctm.client.asm.CTMTransformer:finishTransform:242]: Transforming net.minecraftforge.client.ForgeHooksClient Finished.
[22:16:53] [Client thread/INFO]: Setting user: Neptune8_
[22:16:53] [Client thread/INFO]: Patching net.minecraft.block.Block... (aow)
[22:16:53] [Client thread/INFO]: [team.chisel.ctm.client.asm.CTMTransformer:preTransform:230]: Transforming Class [net.minecraft.block.Block], Method [getExtendedState]
[22:16:53] [Client thread/INFO]: [team.chisel.ctm.client.asm.CTMTransformer:finishTransform:242]: Transforming net.minecraft.block.Block Finished.
[22:16:53] [Client thread/INFO]: Patching math utils with "RIVENS_HALF" algorithm
[22:16:54] [Client thread/INFO]: Patching net.minecraft.tileentity.TileEntityBeacon... (avh)
[22:16:54] [Client thread/INFO]: Patching net.minecraft.block.BlockHopper... (arl)
[22:16:54] [Client thread/INFO]: Patching net.minecraft.tileentity.TileEntityHopper... (avw)
[22:16:55] [Client thread/INFO]: Patching GameSettings.datafix
[22:16:56] [Client thread/WARN]: Skipping bad option: lastServer:
[22:16:56] [Client thread/INFO]: LWJGL Version: 2.9.4
[22:16:56] [BetterFps Update Checker/WARN]: Could not check for updates: Server returned HTTP response code: 403 for URL: http://widget.mcf.li/mc-mods/minecraft/229876-betterfps.json
[22:16:56] [Client thread/WARN]: Unable to call Core API! It has not been initialized yet!
[22:16:56] [Client thread/INFO]: -- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1830960984 bytes (1746 MB) / 2075131904 bytes (1979 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 11 total; -Xms1024M -Xmx4096M -XX:MaxPermSize=256M -XX:+UseParallelGC -XX:ParallelGCThreads=6 -XX:+UseSplitVerifier -XX:+FailOverToOldVerifier -XX:-HeapDumpOnOutOfMemoryError -XX:+UseCompressedOops -XX:+ScavengeBeforeFullGC -XX:+PrintCommandLineFlags
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks.jar)
  invtweaks.forge.asm.ContainerTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
MekanismCoremod (Mekanism.jar)
  mekanism.coremod.KeybindingMigrationHelper
Techguns Core (techguns.jar)
  techguns.core.TechgunsASMTransformer
ForgelinPlugin (Forgelin.jar)
  
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  cubex2.cxlibrary.CoreModTransformer
CTMCorePlugin (CTMMC.jar)
  team.chisel.ctm.client.asm.CTMTransformer
MalisisCorePlugin (malisiscore.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 26.20.100.7926' Renderer: 'Intel(R) UHD Graphics 630'
[22:16:56] [Client thread/INFO]: MinecraftForge v14.23.5.2838 Initialized
[22:16:56] [Client thread/INFO]: Starts to replace vanilla recipe ingredients with ore ingredients.
[22:16:57] [Client thread/INFO]: Invalid recipe found with multiple oredict ingredients in the same ingredient...
[22:16:57] [Client thread/INFO]: Replaced 1227 ore ingredients
[22:16:57] [Client thread/INFO]: Searching C:\Users\kevin\AppData\Roaming\.jurassiccraft3\mods for mods
[22:16:58] [Client thread/WARN]: Mod betterbuilderswands is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 0.11.1
[22:16:59] [Thread-3/INFO]: Using sync timing. 200 frames of Display.update took 62258500 nanos
[22:16:59] [Client thread/WARN]: Mod codechickenlib is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 3.2.2.353
[22:16:59] [Client thread/WARN]: Mod damageindicatorsmod is missing the required element 'version' and no fallback can be found. Substituting '1.0'.
[22:16:59] [Client thread/WARN]: Mod ironchest is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.12.2-7.0.67.844
[22:17:00] [Client thread/WARN]: Mod mekanismgenerators is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.12.2-9.8.1.383
[22:17:00] [Client thread/WARN]: Mod mekanismtools is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.12.2-9.8.1.383
[22:17:00] [Client thread/INFO]: Forge Mod Loader has identified 63 mods to load
[22:17:01] [Client thread/INFO]: FML has found a non-mod file ArchimedesShips.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
[22:17:01] [Client thread/INFO]: FML has found a non-mod file neiaddonsmc.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
[22:17:01] [Client thread/INFO]: Attempting connection with missing mods [minecraft, mcp, FML, forge, techguns_core, actuallyadditions, aquaculture, attributefix, betteradvancements, betterbuilderswands, bibliocraft, bonsaitrees, bookshelf, bookworm, chameleon, chisel, codechickenlib, controlling, ctm, cxlibrary, damageindicatorsmod, props, elevatorid, eplus, extrautils2, fastleafdecay, forgelin, fossil, cfm, gravestone, hats, ic2, ic2-classic-spmod, ichunutil, industrialforegoing, inventorytweaks, ironchest, jei, journeymap, malisiscore, malisisdoors, mekanism, mekanismgenerators, mekanismtools, morefurnaces, nei, harvestcraft, ptrmodellib, reborncore, roguelike, securitycraft, stevescarts, storagedrawers, techguns, teslacorelib, teslacorelib_registries, travellersbackpack, tropicraft, twilightforest, zawa, zoocraftdiscoveries, jurassicraft, llibrary] at CLIENT
[22:17:01] [Client thread/INFO]: Attempting connection with missing mods [minecraft, mcp, FML, forge, techguns_core, actuallyadditions, aquaculture, attributefix, betteradvancements, betterbuilderswands, bibliocraft, bonsaitrees, bookshelf, bookworm, chameleon, chisel, codechickenlib, controlling, ctm, cxlibrary, damageindicatorsmod, props, elevatorid, eplus, extrautils2, fastleafdecay, forgelin, fossil, cfm, gravestone, hats, ic2, ic2-classic-spmod, ichunutil, industrialforegoing, inventorytweaks, ironchest, jei, journeymap, malisiscore, malisisdoors, mekanism, mekanismgenerators, mekanismtools, morefurnaces, nei, harvestcraft, ptrmodellib, reborncore, roguelike, securitycraft, stevescarts, storagedrawers, techguns, teslacorelib, teslacorelib_registries, travellersbackpack, tropicraft, twilightforest, zawa, zoocraftdiscoveries, jurassicraft, llibrary] at SERVER
[22:17:02] [Client thread/ERROR]: The mod bookshelf is expecting signature d476d1b22b218a10d845928d1665d45fce301b27 for source Bookshelf-1.12.2-2.3.557-deobf.jar, however there is no signature matching that description
[22:17:02] [Client thread/ERROR]: Invalid fingerprint detected! The file Bookshelf-1.12.2-2.3.557-deobf.jar may have been tampered with. This version will NOT be supported by the author!
[22:17:03] [Client thread/INFO]: Reloading ResourceManager: BetterFps, Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Actually Additions, FMLFileResourcePack:Aquaculture, FMLFileResourcePack:Attribute Fix, FMLFileResourcePack:Better Advancements, FMLFileResourcePack:Better Builder's Wands, FMLFileResourcePack:BiblioCraft, FMLFileResourcePack:Bonsai Trees, FMLFileResourcePack:Bookshelf, FMLFileResourcePack:Bookworm API, FMLFileResourcePack:Chameleon, FMLFileResourcePack:Chisel, FMLFileResourcePack:CodeChicken Lib, FMLFileResourcePack:Controlling, FMLFileResourcePack:CTM, FMLFileResourcePack:CXLibrary, FMLFileResourcePack:Damage Indicators Mod, FMLFileResourcePack:Decocraft, FMLFileResourcePack:Elevator Mod, FMLFileResourcePack:Enchanting Plus, FMLFileResourcePack:Extra Utilities 2, FMLFileResourcePack:Fast Leaf Decay, FMLFileResourcePack:Shadowfacts' Forgelin, FMLFileResourcePack:Fossils and Archeology Revival, FMLFileResourcePack:MrCrayfish's Furniture Mod, FMLFileResourcePack:Gravestone Mod, FMLFileResourcePack:Hats, FMLFileResourcePack:IndustrialCraft 2 Classic, FMLFileResourcePack:IC2 Classic Detection Helper, FMLFileResourcePack:iChunUtil, FMLFileResourcePack:Industrial Foregoing, FMLFileResourcePack:Inventory Tweaks, FMLFileResourcePack:Iron Chest, FMLFileResourcePack:Just Enough Items, FMLFileResourcePack:JourneyMap, FMLFileResourcePack:MalisisCore, FMLFileResourcePack:MalisisDoors, FMLFileResourcePack:Mekanism, FMLFileResourcePack:Mekanism: Generators, FMLFileResourcePack:Mekanism: Tools, FMLFileResourcePack:More Furnaces, FMLFileResourcePack:Not Enough Items, FMLFileResourcePack:Pam's HarvestCraft, FMLFileResourcePack:ptrmodellib, FMLFileResourcePack:Reborn Core, FMLFileResourcePack:Roguelike Dungeons, FMLFileResourcePack:SecurityCraft, FMLFileResourcePack:Steve's Carts 2, FMLFileResourcePack:Storage Drawers, FMLFileResourcePack:Techguns, FMLFileResourcePack:Tesla Core Lib, FMLFileResourcePack:Tesla Core Lib Registries, FMLFileResourcePack:Traveller's Backpack, FMLFileResourcePack:Tropicraft, FMLFileResourcePack:The Twilight Forest, FMLFileResourcePack:Zoo and Wild Animals Mod: Rebuilt, FMLFileResourcePack:Zoocraft Discoveries, FMLFileResourcePack:JurassiCraft, FMLFileResourcePack:LLibrary
[22:17:03] [Client thread/INFO]: [techguns.core.TechgunsASMTransformer:patchRenderItem_patchMethodRenderModel:480]: Successfully patched 2 arg RenderItem.RenderModel with ASM
[22:17:03] [Client thread/INFO]: [techguns.core.TechgunsASMTransformer:patchRenderItem_patchMethodRenderItem:299]: Successfully patched 4 arg RenderItem.RenderItem with ASM
[22:17:03] [Client thread/INFO]: [techguns.core.TechgunsASMTransformer:patchRenderItem_patchMethodRenderItemGUI:423]: Successfully patched RenderItem.renderItemModelIntoGUI with ASM
[22:17:03] [Client thread/INFO]: Patching net.minecraft.client.renderer.EntityRenderer... (buq)
[22:17:03] [Client thread/WARN]: Unable to call Core API! It has not been initialized yet!
[22:17:03] [Client thread/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----
WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  MekanismCoremod (Mekanism.jar)
  Techguns Core (techguns.jar)
  ForgelinPlugin (Forgelin.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  CTMCorePlugin (CTMMC.jar)
  MalisisCorePlugin (malisiscore.jar)
Contact their authors BEFORE contacting forge
// Don't do that.
Time: 10/26/20 10:17 PM
Description: Initializing game
java.lang.NoSuchMethodError: net.minecraft.util.NonNullList.create()Lnet/minecraft/util/NonNullList;
	at net.darkhax.bookshelf.registry.RegistryHelper.<clinit>(RegistryHelper.java:62)
	at net.darkhax.eplus.EnchantingPlus.<clinit>(EnchantingPlus.java:39)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Client thread
Stacktrace:
	at net.darkhax.bookshelf.registry.RegistryHelper.<clinit>(RegistryHelper.java:62)
	at net.darkhax.eplus.EnchantingPlus.<clinit>(EnchantingPlus.java:39)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 902966696 bytes (861 MB) / 2073034752 bytes (1977 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 11 total; -Xms1024M -Xmx4096M -XX:MaxPermSize=256M -XX:+UseParallelGC -XX:ParallelGCThreads=6 -XX:+UseSplitVerifier -XX:+FailOverToOldVerifier -XX:-HeapDumpOnOutOfMemoryError -XX:+UseCompressedOops -XX:+ScavengeBeforeFullGC -XX:+PrintCommandLineFlags
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 63 mods loaded, 63 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	| State | ID                      | Version                  | Source                                        | Signature                                |
	|:----- |:----------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft               | 1.12.2                   | minecraft.jar                                 | None                                     |
	| LC    | mcp                     | 9.42                     | minecraft.jar                                 | None                                     |
	| LC    | FML                     | 8.0.99.99                | forge-1.12.2-14.23.5.2838-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                   | 14.23.5.2838             | forge-1.12.2-14.23.5.2838-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | techguns_core           | 1.12.2-1.0               | minecraft.jar                                 | None                                     |
	| LC    | actuallyadditions       | 1.12.2-r149              | ActuallyAdditionsr.jar                        | None                                     |
	| LC    | aquaculture             | 1.6.8                    | Aquaculture.jar                               | None                                     |
	| LC    | attributefix            | 1.0.4                    | AttributeFix-1.12.2-1.0.4.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | betteradvancements      | 0.1.0.77                 | BetterAdvancements.jar                        | None                                     |
	| LC    | betterbuilderswands     | 0.11.1                   | BetterBuildersWandsdd.jar                     | None                                     |
	| LC    | bibliocraft             | 2.4.5                    | BiblioCraftvMC.jar                            | None                                     |
	| LC    | bonsaitrees             | 1.1.3                    | bonsaitreesb.jar                              | None                                     |
	| LC    | bookshelf               | 2.3.557                  | Bookshelf-1.12.2-2.3.557-deobf.jar            | None                                     |
	| LC    | bookworm                | 1.12.2-2.3.0             | bookworm.jar                                  | None                                     |
	| LC    | chameleon               | 1.12-4.1.3               | Chameleon.jar                                 | None                                     |
	| LC    | ctm                     | MC1.12.2-0.3.3.22        | CTMMC.jar                                     | None                                     |
	| LC    | chisel                  | MC1.12.2-0.2.1.35        | ChiselMC.jar                                  | None                                     |
	| LC    | codechickenlib          | 3.2.2.353                | CodeChickenLib.jar                            | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | controlling             | 3.0.6                    | Controlling.jar                               | None                                     |
	| LC    | cxlibrary               | 1.6.1                    | cxlibrary-1.12.1-1.6.1.jar                    | None                                     |
	| LC    | damageindicatorsmod     | 1.0                      | DamageIndicatorsMod.jar                       | None                                     |
	| LC    | ptrmodellib             | 1.0.4                    | PTRLib.jar                                    | None                                     |
	| LC    | props                   | 2.6.3                    | Decocraft.jar                                 | None                                     |
	| LC    | elevatorid              | 1.3.10                   | ElevatorMod.jar                               | None                                     |
	| L     | eplus                   | 5.0.176                  | EnchantingPlus-1.12.2-5.0.176.jar             | None                                     |
	| L     | extrautils2             | 1.0                      | extrautils2-1.12-1.9.9.jar                    | None                                     |
	| L     | fastleafdecay           | v14                      | FastLeafDecay-v14.jar                         | None                                     |
	| L     | forgelin                | 1.8.3                    | Forgelin.jar                                  | None                                     |
	| L     | llibrary                | 1.7.19                   | llibrary.jar                                  | None                                     |
	| L     | fossil                  | 8.0.3                    | fossilsarcheology.jar                         | None                                     |
	| L     | cfm                     | 6.3.0                    | furniture.jar                                 | None                                     |
	| L     | gravestone              | 1.10.1                   | gravestone.jar                                | None                                     |
	| L     | ichunutil               | 7.2.1                    | iChunUtil.jar                                 | None                                     |
	| L     | hats                    | 7.0.0                    | Hats.jar                                      | None                                     |
	| L     | ic2                     | 2.8.1000                 | ICClassic.jar                                 | None                                     |
	| L     | ic2-classic-spmod       | 0.0.0.0                  | ICClassic.jar                                 | None                                     |
	| L     | jei                     | 4.15.0.268               | jei.jar                                       | None                                     |
	| L     | mekanism                | 1.12.2-9.8.1.383         | Mekanism.jar                                  | None                                     |
	| L     | teslacorelib            | 1.0.15                   | teslacorelib.jar                              | None                                     |
	| L     | industrialforegoing     | 1.12.2-1.12.2            | industrialforegoing.jar                       | None                                     |
	| L     | inventorytweaks         | 1.63+release.109.220f184 | InventoryTweaks.jar                           | None                                     |
	| L     | ironchest               | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar               | None                                     |
	| L     | journeymap              | 1.12.2-5.5.4             | journeymap.jar                                | None                                     |
	| L     | malisiscore             | 1.12.2-6.5.1-SNAPSHOT    | malisiscore.jar                               | None                                     |
	| L     | malisisdoors            | 1.12.2-7.3.0             | malisisdoors.jar                              | None                                     |
	| L     | mekanismgenerators      | 1.12.2-9.8.1.383         | MekanismGenerators.jar                        | None                                     |
	| L     | mekanismtools           | 1.12.2-9.8.1.383         | MekanismTools.jar                             | None                                     |
	| L     | morefurnaces            | 1.10.5                   | MoreFurnaces-1.12.2-1.10.6.jar                | None                                     |
	| L     | nei                     | 2.4.2                    | NotEnoughItemsuniversal.jar                   | None                                     |
	| L     | harvestcraft            | 1.12.2zb                 | PamsHarvestCraftzdSurpriseforYogcast.jar      | None                                     |
	| L     | reborncore              | 3.14.1.457               | RebornCoreuniversal.jar                       | None                                     |
	| L     | roguelike               | 1.8.0                    | RoguelikeDungeons.jar                         | None                                     |
	| L     | securitycraft           | v1.8.12                  | SecurityCraftv.jar                            | None                                     |
	| L     | stevescarts             | 2.4.31.135               | StevesCarts.jar                               | None                                     |

**Comment by Darkhax** [comment]
You have the deobf version of Bookshelf installed, that's for mod devs who want to test compatibility and won't work for normal setups. Just download the normal file and you should be fine.
