### ISSUE TITLE
On click NPE with 1.16.4(MC)/35.1.5(Forge)/1.16.4-9.2.14(Bookshelf)

### ISSUE THREAD

**Issue by Letoric** [Darkhax-Minecraft/Bookshelf#154]
[10:13:18] [Server thread/INFO] [STDERR/]: [net.darkhax.bookshelf.Bookshelf:onClick:121]: java.lang.NullPointerException
[10:13:18] [Server thread/INFO] [STDERR/]: [net.darkhax.bookshelf.Bookshelf:onClick:121]:       at net.darkhax.bookshelf.serialization.BlockIngredientSerializer.read(BlockIngredientSerializer.java:24)
[10:13:18] [Server thread/INFO] [STDERR/]: [net.darkhax.bookshelf.Bookshelf:onClick:121]:       at net.darkhax.bookshelf.serialization.BlockIngredientSerializer.read(BlockIngredientSerializer.java:11)
[10:13:18] [Server thread/INFO] [STDERR/]: [net.darkhax.bookshelf.Bookshelf:onClick:121]:       at net.darkhax.bookshelf.Bookshelf.onClick(Bookshelf.java:114)
[10:13:18] [Server thread/INFO] [STDERR/]: [net.darkhax.bookshelf.Bookshelf:onClick:121]:       at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
[10:13:18] [Server thread/INFO] [STDERR/]: [net.darkhax.bookshelf.Bookshelf:onClick:121]:       at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
[10:13:18] [Server thread/INFO] [STDERR/]: [net.darkhax.bookshelf.Bookshelf:onClick:121]:       at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
[10:13:18] [Server thread/INFO] [STDERR/]: [net.darkhax.bookshelf.Bookshelf:onClick:121]:       at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:789)
[10:13:18] [Server thread/INFO] [STDERR/]: [net.darkhax.bookshelf.Bookshelf:onClick:121]:       at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:318)
[10:13:18] [Server thread/INFO] [STDERR/]: [net.darkhax.bookshelf.Bookshelf:onClick:121]:       at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:958)
[10:13:18] [Server thread/INFO] [STDERR/]: [net.darkhax.bookshelf.Bookshelf:onClick:121]:       at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36)
[10:13:18] [Server thread/INFO] [STDERR/]: [net.darkhax.bookshelf.Bookshelf:onClick:121]:       at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10)
[10:13:18] [Server thread/INFO] [STDERR/]: [net.darkhax.bookshelf.Bookshelf:onClick:121]:       at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21)
[10:13:18] [Server thread/INFO] [STDERR/]: [net.darkhax.bookshelf.Bookshelf:onClick:121]:       at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
[10:13:18] [Server thread/INFO] [STDERR/]: [net.darkhax.bookshelf.Bookshelf:onClick:121]:       at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
[10:13:18] [Server thread/INFO] [STDERR/]: [net.darkhax.bookshelf.Bookshelf:onClick:121]:       at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
[10:13:18] [Server thread/INFO] [STDERR/]: [net.darkhax.bookshelf.Bookshelf:onClick:121]:       at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:733)
[10:13:18] [Server thread/INFO] [STDERR/]: [net.darkhax.bookshelf.Bookshelf:onClick:121]:       at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159)
[10:13:18] [Server thread/INFO] [STDERR/]: [net.darkhax.bookshelf.Bookshelf:onClick:121]:       at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
[10:13:18] [Server thread/INFO] [STDERR/]: [net.darkhax.bookshelf.Bookshelf:onClick:121]:       at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:716)
[10:13:18] [Server thread/INFO] [STDERR/]: [net.darkhax.bookshelf.Bookshelf:onClick:121]:       at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:710)
[10:13:18] [Server thread/INFO] [STDERR/]: [net.darkhax.bookshelf.Bookshelf:onClick:121]:       at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103)
[10:13:18] [Server thread/INFO] [STDERR/]: [net.darkhax.bookshelf.Bookshelf:onClick:121]:       at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:695)
[10:13:18] [Server thread/INFO] [STDERR/]: [net.darkhax.bookshelf.Bookshelf:onClick:121]:       at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:645)
[10:13:18] [Server thread/INFO] [STDERR/]: [net.darkhax.bookshelf.Bookshelf:onClick:121]:       at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232)
[10:13:18] [Server thread/INFO] [STDERR/]: [net.darkhax.bookshelf.Bookshelf:onClick:121]:       at java.lang.Thread.run(Unknown Source)

**Comment by Letoric** [comment]
I'm testing with .15 build now, hopefully it's resolved, and if so sorry for the post without latest version.

**Comment by Letoric** [comment]
Not seeing it in .15 build, but not 100% what I was clicking on that caused it previously so I'll leave it up to you to close or not.

**Comment by Darkhax** [comment]
Thanks for resolving, this issue was fixed shortly before you opened this issue. https://github.com/Darkhax-Minecraft/Bookshelf/issues/153
