### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by DPxKnightxZero** [Darkhax-Minecraft/Bookshelf#25]
Full info available. Need fix asap or just tell me which mods use your library so I can remove it. Here is the mod list.

https://gist.github.com/DPxKnightxZero/b7a7e40315552622f3c6

**Comment by darkhax** [comment]
Please post your crash log, we can't help you without it.

**Comment by DPxKnightxZero** [comment]
[19:53:40] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/potion/Potion
	at net.minecraft.potion.PotionHelper.<clinit>(SourceFile:82) ~[aen.class:?]
	at net.minecraft.item.Item.func_150900_l(Item.java:129) ~[adb.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:358) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.potion.Potion
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at net.minecraft.potion.PotionHelper.<clinit>(SourceFile:82) ~[aen.class:?]
	at net.minecraft.item.Item.func_150900_l(Item.java:129) ~[adb.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:358) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 6 more
Caused by: net.darkhax.bookshelf.asm.ASMHelper$InvalidNeedleException: The needle was not found
	at net.darkhax.bookshelf.asm.ASMHelper.findLastNodeFromNeedle(ASMHelper.java:142) ~[%5BUniversal%5D-Bookshelf-1.7.10-1.0.4.172.jar:?]
	at net.darkhax.bookshelf.asm.transformers.PotionTransformer.transformConstructor(PotionTransformer.java:45) ~[%5BUniversal%5D-Bookshelf-1.7.10-1.0.4.172.jar:?]
	at net.darkhax.bookshelf.asm.transformers.PotionTransformer.transform(PotionTransformer.java:17) ~[%5BUniversal%5D-Bookshelf-1.7.10-1.0.4.172.jar:?]
	at net.darkhax.bookshelf.asm.BookshelfTransformerManager.transform(BookshelfTransformerManager.java:31) ~[%5BUniversal%5D-Bookshelf-1.7.10-1.0.4.172.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at net.minecraft.potion.PotionHelper.<clinit>(SourceFile:82) ~[aen.class:?]
	at net.minecraft.item.Item.func_150900_l(Item.java:129) ~[adb.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:358) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 6 more

**Comment by DPxKnightxZero** [comment]
I was trying the latest stable. For this same crash.

**Comment by DPxKnightxZero** [comment]
Full Client Log -> https://gist.github.com/DPxKnightxZero/0338be61d354242b0782

Crash log Unofficial ... Whole Client is freezing before ending launch sequence. 
https://gist.github.com/DPxKnightxZero/91aabcdc2cfe6b02e497

**Comment by darkhax** [comment]
This is a conflict with AIC Core. You can go into bookshelf_asm.cfg and change potionDetectionEnabled to false. That should fix your issue.

**Comment by DPxKnightxZero** [comment]
Okay thank you. That fixed it.
