### ISSUE TITLE
Game keeps crashing

### ISSUE THREAD

**Issue by Zianthite** [Darkhax-Minecraft/Bookshelf#36]
I tried to play minecraft with mods and it said that I needed to have bookshelf to play, but when I downloaded bookshelf, my minecraft crashed.
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: thehippomaster/MutantCreatures/MutantSkeleton
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: thehippomaster/MutantCreatures/MutantSkeleton
	at thehippomaster.MutantCreatures.item.ChemicalX.<clinit>(ChemicalX.java:83)
	at thehippomaster.MutantCreatures.MutantCreatures.preInit(MutantCreatures.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 10 more
Caused by: java.lang.ClassNotFoundException: thehippomaster.MutantCreatures.MutantSkeleton
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 38 more
Caused by: java.lang.NoClassDefFoundError: thehippomaster/AnimationAPI/IAnimatedEntity
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 40 more
Caused by: java.lang.ClassNotFoundException: thehippomaster.AnimationAPI.IAnimatedEntity
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 385265080 bytes (367 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	Mod Pack: ~~ERROR~~ NullPointerException: null
	LiteLoader Mods: ~~ERROR~~ NullPointerException: null
	LaunchWrapper: 41 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: net.minecraftforge.classloading.FluidIdTransformer
          - Transformer: mods.battlegear2.coremod.transformers.EntityPlayerTransformer
          - Transformer: mods.battlegear2.coremod.transformers.ModelBipedTransformer
          - Transformer: mods.battlegear2.coremod.transformers.NetClientHandlerTransformer
          - Transformer: mods.battlegear2.coremod.transformers.NetServerHandlerTransformer
          - Transformer: mods.battlegear2.coremod.transformers.PlayerControllerMPTransformer
          - Transformer: mods.battlegear2.coremod.transformers.ItemRendererTransformer
          - Transformer: mods.battlegear2.coremod.transformers.MinecraftTransformer
          - Transformer: mods.battlegear2.coremod.transformers.ItemInWorldTransformer
          - Transformer: mods.battlegear2.coremod.transformers.EntityAIControlledByPlayerTransformer
          - Transformer: mods.battlegear2.coremod.transformers.EntityOtherPlayerMPTransformer
          - Transformer: mods.battlegear2.coremod.transformers.EntityTrackerTransformer
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: mods.battlegear2.coremod.transformers.BattlegearAccessTransformer
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: net.malisis.core.asm.MalisisCoreAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: net.darkhax.bookshelf.asm.BookshelfTransformerManager
          - Transformer: net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
          - Transformer: net.malisis.core.util.chunkblock.ChunkBlockTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 48 mods loaded, 48 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCH	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCH	FamiliarsAPI{1.7.10} [Familiars API] (FamiliarsAPI-1.7.10.jar) 
	UCH	battlegear2{1.0.5.6} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.5.6.jar) 
	UCH	dungeonpack{1.7.10-1.0} [Dungeon Pack] (14174895548_Dungeon-Pack-Mod-1.7.10 (1).jar) 
	UCH	lucky{5.1.0} [Lucky Block] ([1-7-10]_Lucky_Block_v5-1-0.jar) 
	UCH	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCH	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCH	DamageIndicatorsMod{3.2.0} [Damage Indicators] (_Damage-Indicators-Mod-1.7.10.jar) 
	UCH	pandorasbox{2.0.1} [Pandora's Box] (_Pandoras-Box-Mod-1.7.10.jar) 
	UCH	animatedplayer{1.5.1} [Animated Player Mod] (AnimatedPlayer-1.7.10-1.5.1.jar) 
	UCH	nevermine{2.3} [AdventOfAscension] (AoA-2.4.B.jar) 
	UCH	gibby_dungeons{1.5} [Arcana RPG] (Arcana RPG 1.5 - 1.7.10.jar) 
	UCH	Backpack{2.0.1} [Backpack] (Backpacks-Mod.jar) 
	UCH	iChunUtil{4.1.3} [iChunUtil] (iChun-Util-Mod-1.7.10.jar) 
	UCH	BackTools{4.0.0} [BackTools] (BackTools-4.0.0.jar) 
	UCH	bookshelf{1.0.4.172} [Bookshelf] (Bookshelf-1.7.10-1.0.4.172.jar) 
	UCH	cfm{3.4.8} [§9MrCrayfish's Furniture Mod] (cfm-3.4.8-mc1.7.10.jar) 
	UCH	CustomPets{1.0.3} [Custom Pets] (custompets-1.7.10-1.0.3-universal.jar) 
	UCH	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.2.1_1.7.10.jar) 
	UCH	props{2.2.1} [Decocraft] (Decocraft-2.2.1_1.7.10.jar) 
	UCH	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCH	golems{1.20} [Extra Golems] (Extra-Golems[1.7.10]-1.20.jar) 
	UCH	DefaultMobPack{1.7.10} [DefaultMobPack] (FamiliarsDefaultMobPack-1.7.10.jar) 
	UCH	ExtendedFamPack{1.7.10} [ExtendedFamPack] (FamiliarsExtendedFamPack-1.7.10.jar) 
	UCH	HerobrineFamPack{1.7.10} [HerobrineFamPack] (FamiliarsHerobrineFamPack-1.7.10.jar) 
	UCH	grim3212core{V0.2 - 1.7.10} [Grim3212 Core] (Grim3212-Core-1.7.10.jar) 
	UCH	Hats{4.0.1} [Hats] (Hats-4.0.1.jar) 
	UCH	headcrumbs{1.7.4} [Headcrumbs] (Headcrumbs-1.7.4.jar) 
	UCH	InfernalMobs{1.6.0} [Infernal Mobs] (InfernalMobs-1.7.10.jar) 
	UCH	lootbags{2.0.8} [Loot Bags] (LootBags-1.7.10-2.0.8.jar) 
	UCH	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
	UCH	malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2.jar) 
	UCH	MobAmputation{4.0.1} [MobAmputation] (MobAmputation-4.0.1.jar) 
	UCH	MobDismemberment{4.0.0} [MobDismemberment] (MobDismemberment-4.0.0.jar) 
	UCH	Morph{0.9.1} [Morph] (Morphing-Mod-1.7.10.jar) 
	UCE	MutantCreatures{1.4.9} [Mutant Creatures] (MutantCreatures-1.7.10-1.4.9.jar) 
	UCH	mwaw{1.7.10-0.0.7} [Elemental Witch Mod] (mwaw-0.0.7-1.7.10.jar) 
	UCH	pokeball{V0.1 - 1.7.10} [Pokeball] (Pokeball-Mod-by-grim3212-1.7.10.jar) 
	UCH	RottenFleshToLeather{1.7.10-2.0} [Rotten Flesh to Leather] (RottenFleshToLeather-2.1-1.7.10.jar) 
	UCH	AS_Ruins{15.4} [Ruins Spawning System] (Ruins-1.7.10.jar) 
	UCH	telepads{1.0.0} [Telepads] (Telepads 1.7.10 Full Release 3.1.jar) 
	UCH	Torched{4.0.0} [Torched] (Torched-Mod-1.7.10.jar) 
	UCH	AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.7.10.jar) 
	UCH	youtubers{1.8.0} [Youtubers+ Mod] (youtubers-1.8.0-MC1.7.10.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4331' Renderer: 'Intel(R) HD Graphics 4600'

**Comment by Spartan322** [comment]
This is not a Bookshelf problem, this is a mutant creature problem.

**Comment by darkhax** [comment]
1.7.10 is not a supported version of Minecraft. This also appears to be more of an issue with Mutant Creatures or an ASM conflict. In either scenario there is nothing I can do to help you.
