### ISSUE TITLE
NullPointerException: Rendering entity in world

### ISSUE THREAD

**Issue by TomberWolf** [Darkhax-Minecraft/Bookshelf#60]
```
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:249)
	at net.minecraft.client.renderer.ItemModelMesher.func_178084_b(ItemModelMesher.java:66)
	at net.minecraft.client.renderer.ItemModelMesher.func_178089_a(ItemModelMesher.java:44)
	at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:352)
	at codechicken.lib.render.item.CCRenderItem.func_184393_a(CCRenderItem.java:297)
	at net.darkhax.bookshelf.client.render.item.RenderItemWrapper.func_184393_a(RenderItemWrapper.java:341)
	at net.minecraft.client.renderer.entity.RenderEntityItem.func_76986_a(RenderEntityItem.java:115)
	at net.minecraft.client.renderer.entity.RenderEntityItem.func_76986_a(RenderEntityItem.java:19)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:398)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:375)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:811)
	at shadersmod.client.ShadersRender.renderShadowMap(ShadersRender.java:361)
	at shadersmod.client.Shaders.beginRender(Shaders.java:4051)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1545)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1345)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:249)
	at net.minecraft.client.renderer.ItemModelMesher.func_178084_b(ItemModelMesher.java:66)
	at net.minecraft.client.renderer.ItemModelMesher.func_178089_a(ItemModelMesher.java:44)
	at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:352)
	at codechicken.lib.render.item.CCRenderItem.func_184393_a(CCRenderItem.java:297)
	at net.darkhax.bookshelf.client.render.item.RenderItemWrapper.func_184393_a(RenderItemWrapper.java:341)
	at net.minecraft.client.renderer.entity.RenderEntityItem.func_76986_a(RenderEntityItem.java:115)
	at net.minecraft.client.renderer.entity.RenderEntityItem.func_76986_a(RenderEntityItem.java:19)

-- Entity being rendered --
Details:
	Entity Type: Item (net.minecraft.entity.item.EntityItem)
	Entity ID: 6087
	Entity Name: ~~ERROR~~ NullPointerException: null
	Entity's Exact location: 140.79, 85.00, -1432.58
	Entity's Block location: World: (140,85,-1433), Chunk: (at 12,5,7 in 8,-90; contains blocks 128,0,-1440 to 143,255,-1425), Region: (0,-3; contains chunks 0,-96 to 31,-65, blocks 0,0,-1536 to 511,255,-1025)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.RenderEntityItem@4ea2cf2d
	Location: -0.33,0.00,2.41 - World: (-1,0,2), Chunk: (at 15,0,2 in -1,0; contains blocks -16,0,0 to -1,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Rotation: 50.824074
	Delta: 0.75294924
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:398)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:375)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:811)
	at shadersmod.client.ShadersRender.renderShadowMap(ShadersRender.java:361)
	at shadersmod.client.Shaders.beginRender(Shaders.java:4051)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1545)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Tom'/6091, l='MpServer', x=141.11, y=85.00, z=-1434.99]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 07 - RTG, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (64,77,-1360), Chunk: (at 0,4,0 in 4,-85; contains blocks 64,0,-1360 to 79,255,-1345), Region: (0,-3; contains chunks 0,-96 to 31,-65, blocks 0,0,-1536 to 511,255,-1025)
	Level time: 500195 game time, 635331 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: ~~ERROR~~ NullPointerException: null
	Retry entities: 0 total; []
	Server brand: fml,forge,sponge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

```

**Comment by darkhax** [comment]
This would appear to be an issue with Shadersmod's shadow map and not Bookshelf or Code Chicken Lib.
