### ISSUE TITLE
NullPointerException: Rendering entity in world

### ISSUE THREAD

**Issue by TomberWolf** [Darkhax-Minecraft/Bookshelf#62]
Minecraft 1.10.2

```
Description: Rendering entity in world
 
java.lang.NullPointerException: Rendering entity in world
    at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:250)
    at net.minecraft.client.renderer.ItemModelMesher.func_178084_b(ItemModelMesher.java:66)
    at net.minecraft.client.renderer.ItemModelMesher.func_178089_a(ItemModelMesher.java:44)
    at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:352)
    at net.darkhax.bookshelf.client.render.item.RenderItemWrapper.func_184393_a(RenderItemWrapper.java:354)
    at codechicken.lib.render.item.CCRenderItem.func_184393_a(CCRenderItem.java:297)
    at net.minecraft.client.renderer.entity.RenderEntityItem.func_76986_a(RenderEntityItem.java:115)
    at net.minecraft.client.renderer.entity.RenderEntityItem.func_76986_a(RenderEntityItem.java:19)
    at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:398)
    at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:375)
    at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:811)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1741)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1566)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1345)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by darkhax** [comment]
This is not an issue with Bookshelf or CCL. It's an issue with the entity or item being rendered.
