### ISSUE TITLE
Invalid registration attempt for an Ore Dictionary

### ISSUE THREAD

**Issue by bookerthegeek** [Darkhax-Minecraft/Bookshelf#74]
### Heyo ###
Saw this in the log, thought you should know.

```
[13:26:12] [Client thread/WARN] [FML]: ****************************************
[13:26:12] [Client thread/WARN] [FML]: * Invalid registration attempt for an Ore Dictionary item with name blockBed has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
[13:26:12] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:601)
[13:26:12] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:587)
[13:26:12] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:586)
[13:26:12] [Client thread/WARN] [FML]: *  at net.darkhax.bookshelf.features.oredict.FeatureOreDict.onPreInit(FeatureOreDict.java:62)
[13:26:12] [Client thread/WARN] [FML]: *  at net.darkhax.bookshelf.Bookshelf.preInit(Bookshelf.java:42)
[13:26:12] [Client thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
[13:26:12] [Client thread/WARN] [FML]: ****************************************
```
### Versions ###
 - Minecraft 1.11.2
 - Bookshelf-1.11.2-1.5.0.371

**Comment by darkhax** [comment]
Yeah, not too sure what is causing this. I think I might be registering it too early.
